### ISSUE TITLE
cludflare bot detection issue

### ISSUE THREAD

**Issue by thenik** [Hudrolax/uc-docker#1]
Hi!

Thanks for your uc-docker , it looks really interesting.

I tried to run on my server and got the next  

![image](https://github.com/Hudrolax/uc-docker/assets/1731242/2b75a887-0c76-4f42-be98-5f3efdd0e4ca)

https://i.imgur.com/ChT5MAy.png

Looks like your hint to open cludflare via delay and link cliking does not work now.
Any way thanks for your docker file sample.

**Comment by Hudrolax** [comment]
I'm using this build for Discord automation right now. I think the difference is in the IP address. If your host has a large IP pool and tries to bypass Cloudflare, Cloudflare will be suspicious of the IP addresses from this host. You can connect to container thought VNC and pass cloudflare in hand mode one time. Maybe it will works for you.

**Comment by Ali-Flt** [comment]
@Hudrolax can you please give a brief explanation of how can we connect to the container using VNC to pass cloudflare? 

Do you mean that it is possible to interact with the running undetected chromedriver while the python code is running?

Any elaboration on this is much appreciated.

**Comment by Hudrolax** [comment]
@Ali-Flt Yes, you can connect via VNC to your image insaide Docker and view "the desktop" and cromium window and to interact with it. In docker-compose.yml you can map VNC port inside container. In default this port is 5900.
Usually, if you are trying to bypass verification for the first time from a given IP, then Cloudflare will ask you to complete a captcha. If you are using a VPS server in the cloud, then often the range of their IPs will be suspicious for Cloudflare. Try not to use IP cloud services.

**Comment by Ali-Flt** [comment]
@Hudrolax thanks. I used vncviewer to connect to 127.0.0.01:5900 and opened a shell and ran `google-chrome --no-sandbox` to open chrome. Then went to the website I want to connect to and checked the cloudflare checkbox. After that I used `docker exec` to connect to my container and ran `python main.py` to use undetected_chromedriver to connect to the same website but I encountered this again. 
![image](https://github.com/Hudrolax/uc-docker/assets/60854595/e8921139-2415-41a3-a01c-1fb492af81f0)

I don't understand what does connecting to VNC and interacting with the webpage inside the chrome GUI have to do with the python code. Did I do any steps incorrect?

**Comment by Ali-Flt** [comment]
I believe my problem was that I was running undetected chromedriver in headless mode.

**Comment by Hudrolax** [comment]
Overall, you can use headless mode if Cloudflare allows you through by default. But then you can't control the process. If Cloudflare stops you, then you need to manually assist the script at the initial stage through VNC. It's especially important to use blank.html, sleep(10-15) and clicking on a link in blank.html (simple script in test.py) and then Selenium switching to another tab using driver.switch_to.window(driver.window_handles[1]). Without all this, Cloudflare will immediately detect the script.

**Comment by Ali-Flt** [comment]
@Hudrolax I tried manually clicking the cloudflare checkbox after opening chrome with uc but it failed as in the following picture:
![IMG_20240424_032332_383](https://github.com/Hudrolax/uc-docker/assets/60854595/be77c977-0db3-40c0-9e77-3918e0840b51)
I also tried using blank.html just like your code but no luck. Even the uc mode of seleniumbase package didn't work. 
My guess is that cloudflare has become smarter in detecting chromedriver. 
Maybe I'm doing something wrong. I would appreciate it if you could try passing the cloudflare check of my target website whenever you had some free time to kill :)
The website is https://visa.vfsglobal.com/IRN/en/fra/login

**Comment by Hudrolax** [comment]
Sorry, but i can't built this image on my MacBook with ARM now.
I used my second alpine version of the image (https://github.com/Hudrolax/uc-docker-alpine) and it's works fine for your URL:
<img width="1274" alt="image" src="https://github.com/Hudrolax/uc-docker/assets/58570622/edf706b1-bf82-4564-bd40-bb15ac625099">
May be your IP adress in the list of suspicious IP addresses of CloudFlare. If you use popular cloud servers, its IPs attract more CloudFlare attention. First try to manually pass the cloudflare verification from the same IP address from which you launch the container with the script.
