### ISSUE TITLE
FileNotFound Error

### ISSUE THREAD

**Issue by oneandonlyjason** [Hudrolax/uc-docker#3]
Hello,

i tried to apply the Docker Container for my Script which works locally on my PC.

```
options = uc.ChromeOptions()
options.add_argument('--disable-gpu')
options.add_argument('--no-sandbox')
options.add_argument('--referer=https://rocketleague.tracker.network/')
driver = uc.Chrome(options=options)
```

I initialize the Driver like this.
But when the Script proceeds i get a Error:

chrome-1  | FileNotFoundError: [Errno 2] No such file or directory: '/root/.loca                                    l/share/undetected_chromedriver/undetected/chromedriver-linux64/chromedriver' ->                                     '/root/.local/share/undetected_chromedriver/undetected_chromedriver'

Any Idee why?

**Comment by Hudrolax** [comment]
You should pass your chromedriver exacutable path into uc.Chrome like this:
```
options = uc.ChromeOptions()
options.arguments.extend(["--no-sandbox", "--disable-setuid-sandbox", "--incognito", "--start-fullscreen"])
driver = uc.Chrome(
   headless=False,
   use_subprocess=False,
   user_multi_procs=True,
   user_data_dir=<path for temp browser files>,
   options=options,
   driver_executable_path='/usr/lib/chromium/chromedriver',
)
```
Besides, you should pass path for Chrome temp folder (create the temp folder in your container).
In my option, i use the Alpine-version of this image - [https://github.com/Hudrolax/uc-docker-alpine](https://github.com/Hudrolax/uc-docker-alpine)

**Comment by oneandonlyjason** [comment]
Well your Idee did fix this Error but now it kinda creates another one:

```
[2024-05-14 17:44:37,255] ERROR in app: Exception on / [GET]
chrome-1  | Traceback (most recent call last):
chrome-1  |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
chrome-1  |     response = self.full_dispatch_request()
chrome-1  |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
chrome-1  |     rv = self.handle_user_exception(e)
chrome-1  |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
chrome-1  |     rv = self.dispatch_request()
chrome-1  |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
chrome-1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
chrome-1  |   File "/app/app.py", line 42, in get_playlist_info
chrome-1  |     driver = uc.Chrome(
chrome-1  |   File "/usr/local/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 258, in __init__
chrome-1  |     self.patcher.auto()
chrome-1  |   File "/usr/local/lib/python3.10/site-packages/undetected_chromedriver/patcher.py", line 136, in auto
chrome-1  |     most_recent = max(files, key=lambda f: f.stat().st_mtime)
chrome-1  | ValueError: max() arg is an empty sequence

```

Maybe you already have an Idee why this Error is there

**Comment by oneandonlyjason** [comment]
Works when i set user_multi_procs=False. That is good enough for me

**Comment by Hudrolax** [comment]
> Works when i set user_multi_procs=False. That is good enough for me

I think it's becouse you use WSGI in your app. I use FastAPI and Uvicorn. I run selenium asynchronous for my microservice.
