### ISSUE TITLE
Error: your connection is not private 

### ISSUE THREAD

**Issue by mohamedaref** [Hudrolax/uc-docker#5]
Hi,

Thanks for the amazing efforts :) 

I run your code and faced some SSL certificate issues " I handled it" but at the end I am still getting the below error (the image generated by the python script "newsecure.png" )

Any ideas about that?

![image](https://github.com/Hudrolax/uc-docker/assets/8994845/4eb8559e-15dd-47eb-8413-1550096d79f5)

**Comment by MohamedArefAbdelgalil** [comment]
I found the solution. Your steps and code are perfect. The issue was some internet options on my local machine that were blocking the image from being installed correctly with an SSL certificate.
I tried a VM instance from Google Cloud, and it worked as expected.
Thanks again :)

**Comment by mohamedaref** [comment]
I found the solution. Your steps and code are perfect. The issue was some internet options on my local machine blocked the docker image from being installed correctly with an SSL certificate.
I tried a VM instance from Google Cloud, and it worked as expected.
Thanks again :)

![image](https://github.com/Hudrolax/uc-docker/assets/8994845/8a3dee84-9ae4-44b3-a180-fe873fd4d35c)
